name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "🚀 Thank you for creaing an Issue. Make sure you have included relavent labels and details to get better and quicker reponse."
        pr-message: " 🚀Thank you for your Pull Request. Your contributions are valuable to us. Make sure that you have made changes in guidance to the CONTRIBUTING.md file. Let's develop this project together. We will review the commits as soon as possible."
